# Generated by Django 3.2.4 on 2021-06-30 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
